/* The written content: riddles, analogies, the word pool the ladders are built
   from, and the names and categories the logic puzzles deal out.

   All of it is plain data with no DOM and no imports, so tools/bloom-sim.mjs
   can load it in Node and check every entry.

   The bar for everything here is that a nine-year-old has to *work* for it.
   Anything answerable by recognising a picture or knowing a fact was cut. */

/* Lateral and logical riddles. Four options, `a` is the index of the true one.
   Roughly ordered easy to hard, because the level picks a window into the list
   rather than carrying a difficulty number on every entry. */
export const RIDDLES = [
  { q: "What gets bigger the more you take away from it?", o: ["A hole", "A cake", "A balloon", "A shadow"], a: 0 },
  { q: "I get wetter the more I dry. What am I?", o: ["A sponge", "A towel", "A puddle", "A cloud"], a: 1 },
  { q: "What can you catch but never throw?", o: ["A ball", "A cold", "A fish", "A bus"], a: 1 },
  { q: "What is so fragile that saying its name breaks it?", o: ["A bubble", "An egg", "Silence", "Ice"], a: 2 },
  { q: "What has many keys but opens no doors?", o: ["A janitor", "A piano", "A keyring", "A car"], a: 1 },
  { q: "What is always in front of you but cannot be seen?", o: ["Air", "The future", "A ghost", "Glass"], a: 1 },
  { q: "What building has the most stories?", o: ["A tower", "A library", "A castle", "A school"], a: 1 },
  { q: "Where does today come before yesterday?", o: ["In a dream", "In a dictionary", "On a calendar", "In the past"], a: 1 },
  { q: "What can go up a chimney down, but not down a chimney up?", o: ["Smoke", "An umbrella", "Santa", "A bird"], a: 1 },
  { q: "I am tall when I am young and short when I am old. What am I?", o: ["A tree", "A candle", "A giraffe", "A shadow"], a: 1 },
  { q: "What has a hundred legs but cannot stand up?", o: ["A centipede", "A caterpillar", "Fifty pairs of trousers", "A ladder"], a: 2 },
  { q: "What is black when clean and white when dirty?", o: ["A blackboard", "A shoe", "A cat", "A window"], a: 0 },
  { q: "What has an end but no beginning and no middle?", o: ["A rope", "A circle", "A doughnut", "A road"], a: 2 },
  { q: "What kind of room has no doors or windows?", o: ["A cellar", "A mushroom", "A cupboard", "A tent"], a: 1 },
  { q: "What is at the end of a rainbow?", o: ["Gold", "The letter W", "Rain", "A pot"], a: 1 },
  { q: "The person who makes it does not want it. The one who buys it does not use it. The one who uses it never knows. What is it?", o: ["A coffin", "A key", "A trap", "A cage"], a: 0 },
  { q: "You are in a race and overtake the runner in second place. What place are you in?", o: ["First", "Second", "Third", "Last"], a: 1 },
  { q: "A farmer has 17 sheep and all but 9 run away. How many are left?", o: ["8", "9", "17", "0"], a: 1 },
  { q: "What can you hold in your left hand but never in your right?", o: ["A pencil", "Your right elbow", "A shadow", "A thought"], a: 1 },
  { q: "Two mothers and two daughters go fishing and catch three fish, one each. How?", o: ["One cheated", "They shared", "There were three of them: a grandma, a mum and a girl", "One fish was cut up"], a: 2 },
  { q: "How many months have 28 days?", o: ["One", "Two", "All twelve", "Four"], a: 2 },
  { q: "If a rooster lays an egg on the ridge of a roof, which way does it roll?", o: ["Left", "Right", "Straight down", "Roosters do not lay eggs"], a: 3 },
  { q: "You see a boat full of people but not one person on board. How?", o: ["They are hiding", "They are all married", "It is a ghost boat", "They swam off"], a: 1 },
  { q: "A man leaves home, turns left three times and comes back to find two masked men waiting. Who are they?", o: ["Burglars", "The catcher and the umpire", "Police", "His brothers"], a: 1 },
  { q: "Before Mount Everest was discovered, what was the tallest mountain in the world?", o: ["K2", "Mount Everest", "Mont Blanc", "Nobody knows"], a: 1 },
  { q: "A doctor gives you three pills and says take one every half hour. How long do they last?", o: ["Half an hour", "One hour", "One and a half hours", "Two hours"], a: 1 },
  { q: "Some months have 30 days, some have 31. How many have 29?", o: ["One", "Four", "Twelve", "None"], a: 2 },
  { q: "A bat and a ball cost £1.10 together. The bat costs £1 more than the ball. What does the ball cost?", o: ["10p", "5p", "1p", "11p"], a: 1 },
  { q: "If it takes 5 machines 5 minutes to make 5 toys, how long do 100 machines take to make 100 toys?", o: ["100 minutes", "5 minutes", "20 minutes", "1 minute"], a: 1 },
  { q: "Lily pads double every day and cover the pond on day 30. When was the pond half covered?", o: ["Day 15", "Day 29", "Day 28", "Day 20"], a: 1 },
  { q: "A snail climbs 3m up a 10m well each day and slips 2m back each night. Which day does it get out?", o: ["Day 10", "Day 8", "Day 9", "Day 7"], a: 1 },
  { q: "You have one match and enter a dark room with an oil lamp, a candle and a fire. What do you light first?", o: ["The lamp", "The match", "The candle", "The fire"], a: 1 },
  { q: "A farmer has ducks and cows: 8 heads and 22 legs. How many cows?", o: ["3", "4", "5", "6"], a: 0 },
  { q: "Which is heavier: a kilo of feathers or a kilo of bricks?", o: ["The feathers", "The bricks", "They are the same", "It depends"], a: 2 },
  { q: "How many times can you subtract 5 from 25?", o: ["Five", "Once — after that it is not 25 any more", "Four", "Twenty-five"], a: 1 },
  { q: "Two people play five games of chess and each wins the same number. There are no draws. How?", o: ["Impossible", "They played different people", "They cheated", "One game was unfinished"], a: 1 },
  { q: "A clock strikes 6 in 5 seconds. How long to strike 12?", o: ["10 seconds", "11 seconds", "12 seconds", "6 seconds"], a: 1 },
  { q: "If you have a bowl with 6 apples and take away 4, how many do you have?", o: ["2", "4", "6", "10"], a: 1 },
  { q: "A rope ladder hangs off a boat with rungs 30cm apart, 3 rungs above water. The tide rises 90cm. How many rungs are above water now?", o: ["None", "One", "Three", "Two"], a: 2 },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", o: ["The letter M", "A second", "A tick", "A blink"], a: 0 },
  { q: "Mary's mother has four children: April, May, June and ...?", o: ["July", "Mary", "August", "Jane"], a: 1 },
  { q: "There are three switches downstairs and one bulb upstairs. You may go up once. How do you find the switch?", o: ["Guess", "Leave one on a while, then switch it off and turn another on — feel for the warm bulb", "Turn all on", "It cannot be done"], a: 1 },
  { q: "A shop sells apples at 3 for 60p. How much do 7 apples cost?", o: ["£1.20", "£1.40", "£2.10", "£1.80"], a: 1 },
  { q: "If two is company and three is a crowd, what are four and five?", o: ["A party", "Nine", "A queue", "A team"], a: 1 },
  { q: "A man pushes his car to a hotel and tells the owner he is bankrupt. What is going on?", o: ["He is lying", "They are playing Monopoly", "The car broke down", "He is joking"], a: 1 },
  { q: "How can you drop a raw egg onto a concrete floor without cracking it?", o: ["Drop it slowly", "Concrete floors are very hard to crack", "Use a net", "You cannot"], a: 1 },
  { q: "A boy and his father are in a crash. The surgeon says 'I cannot operate, he is my son.' How?", o: ["The surgeon is his mother", "He was adopted", "The surgeon is confused", "It is his uncle"], a: 0 },
  { q: "You have a 3-litre and a 5-litre jug. What is the fewest fills and pours to measure exactly 4 litres?", o: ["Impossible", "Fill 5, pour into 3, empty 3, tip the 2 over, fill 5, top up the 3 — 4 left", "Fill 3 twice", "Fill 5 and guess"], a: 1 },
  { q: "Three friends pay £10 each for a £25 room. The porter pockets £2 and returns £1 each. So they paid £27 and the porter has £2 — where is the missing pound?", o: ["The porter stole it", "Nowhere — £27 already includes the porter's £2", "The hotel took it", "There is one missing"], a: 1 },
  { q: "A train leaves at 60mph and another at 40mph towards each other, 100 miles apart. How long until they meet?", o: ["One hour", "Two hours", "Half an hour", "Forty minutes"], a: 0 },
  { q: "In a family each of the 3 sisters has one brother. How many children are there?", o: ["Six", "Four", "Three", "Seven"], a: 1 },
  { q: "You cut a log into 4 pieces. Each cut takes 5 minutes. How long does it take?", o: ["20 minutes", "15 minutes", "10 minutes", "25 minutes"], a: 1 },
  { q: "A bag has 2 red and 2 blue socks. In the dark, how many must you take to be sure of a matching pair?", o: ["Two", "Three", "Four", "One"], a: 1 },
  { q: "If you are 4th in a race of 10 and you overtake the last person, what place are you in?", o: ["Third", "You cannot overtake the last person from 4th", "Fifth", "Fourth"], a: 1 },
  { q: "What weighs more: a tonne of gold or a tonne of feathers on the Moon?", o: ["Gold", "Feathers", "Neither, both are a tonne", "Gold, always"], a: 2 },
  { q: "A cube is painted red and cut into 27 small cubes. How many small cubes have no red at all?", o: ["None", "One", "Six", "Eight"], a: 1 },
  { q: "You have 8 coins and one is lighter. What is the fewest weighings on a balance to find it?", o: ["One", "Two", "Three", "Four"], a: 1 },
  { q: "It takes 3 cats 3 minutes to catch 3 mice. How long for 100 cats to catch 100 mice?", o: ["100 minutes", "3 minutes", "33 minutes", "300 minutes"], a: 1 },
  { q: "Half of 8 is 4. When is half of 8 equal to 3?", o: ["Never", "When you cut the numeral 8 across the middle", "In binary", "When rounding"], a: 1 },
  { q: "A window cleaner falls off a 20m ladder onto concrete and is unhurt. How?", o: ["He was lucky", "He fell off the bottom rung", "He landed on grass", "He wore a helmet"], a: 1 },
];

/* Analogies. `pair` sets the relation, `q` is the word it must be applied to,
   `a` is the answer and `o` the three wrong ones. Every decoy is related to
   the question word somehow, so recognising the *relation* is the only way
   through - picking the word that "goes with" bees does not work. */
export const ANALOGIES = [
  { pair: ["bird", "nest"], q: "bee", a: "hive", o: ["honey", "flower", "sting"], why: "where it lives" },
  { pair: ["puppy", "dog"], q: "kitten", a: "cat", o: ["milk", "paw", "purr"], why: "the grown-up of the young one" },
  { pair: ["hand", "five"], q: "foot", a: "five", o: ["two", "ten", "one"], why: "how many toes and fingers" },
  { pair: ["pen", "write"], q: "knife", a: "cut", o: ["sharp", "kitchen", "metal"], why: "what it is for" },
  { pair: ["hot", "cold"], q: "wide", a: "narrow", o: ["long", "open", "road"], why: "the opposite" },
  { pair: ["book", "paper"], q: "window", a: "glass", o: ["curtain", "room", "open"], why: "what it is made of" },
  { pair: ["fish", "swim"], q: "bird", a: "fly", o: ["feather", "sky", "nest"], why: "how it moves" },
  { pair: ["cow", "moo"], q: "sheep", a: "baa", o: ["wool", "field", "lamb"], why: "the noise it makes" },
  { pair: ["petal", "flower"], q: "leaf", a: "tree", o: ["green", "autumn", "shade"], why: "the whole it is part of" },
  { pair: ["stream", "river"], q: "hill", a: "mountain", o: ["valley", "grass", "climb"], why: "the bigger version" },
  { pair: ["chef", "kitchen"], q: "teacher", a: "classroom", o: ["pupil", "homework", "chalk"], why: "where they work" },
  { pair: ["glove", "hand"], q: "sock", a: "foot", o: ["shoe", "wool", "toe"], why: "the body part it covers" },
  { pair: ["day", "week"], q: "month", a: "year", o: ["calendar", "date", "season"], why: "the longer stretch it fits into" },
  { pair: ["one", "first"], q: "three", a: "third", o: ["thirty", "triple", "many"], why: "the place in an order" },
  { pair: ["wolf", "pack"], q: "fish", a: "shoal", o: ["scale", "ocean", "fin"], why: "the word for a group of them" },
  { pair: ["seed", "plant"], q: "egg", a: "bird", o: ["shell", "nest", "yolk"], why: "what it grows into" },
  { pair: ["doctor", "ill"], q: "mechanic", a: "broken", o: ["car", "garage", "spanner"], why: "what they are called out for" },
  { pair: ["shoe", "leather"], q: "jumper", a: "wool", o: ["warm", "winter", "sleeve"], why: "what it is made of" },
  { pair: ["clock", "time"], q: "ruler", a: "length", o: ["straight", "wood", "school"], why: "what it measures" },
  { pair: ["ice", "water"], q: "steam", a: "water", o: ["hot", "kettle", "cloud"], why: "the same stuff in another state" },
  { pair: ["author", "book"], q: "composer", a: "music", o: ["piano", "orchestra", "concert"], why: "what they make" },
  { pair: ["sun", "day"], q: "moon", a: "night", o: ["crater", "silver", "sky"], why: "when you see it" },
  { pair: ["knife", "fork"], q: "needle", a: "thread", o: ["sharp", "sew", "pin"], why: "the partner it is used with" },
  { pair: ["quiet", "silent"], q: "warm", a: "boiling", o: ["cold", "sunny", "mild"], why: "the stronger version" },
  { pair: ["desert", "dry"], q: "swamp", a: "wet", o: ["frog", "green", "warm"], why: "what it is like there" },
  { pair: ["circle", "sphere"], q: "square", a: "cube", o: ["rectangle", "corner", "flat"], why: "the solid version of the flat shape" },
  { pair: ["cub", "lion"], q: "foal", a: "horse", o: ["saddle", "mane", "gallop"], why: "the grown-up of the young one" },
  { pair: ["forget", "remember"], q: "lose", a: "find", o: ["drop", "search", "keep"], why: "the opposite" },
  { pair: ["bakery", "bread"], q: "dairy", a: "milk", o: ["cow", "farm", "field"], why: "what comes from there" },
  { pair: ["finger", "hand"], q: "spoke", a: "wheel", o: ["bicycle", "metal", "spin"], why: "the whole it is part of" },
  { pair: ["thermometer", "temperature"], q: "scales", a: "weight", o: ["heavy", "kitchen", "balance"], why: "what it measures" },
  { pair: ["library", "books"], q: "museum", a: "exhibits", o: ["quiet", "old", "school"], why: "what is kept there" },
  { pair: ["begin", "end"], q: "arrive", a: "leave", o: ["travel", "late", "station"], why: "the opposite" },
  { pair: ["caterpillar", "butterfly"], q: "tadpole", a: "frog", o: ["pond", "tail", "jelly"], why: "what it turns into" },
  { pair: ["gaggle", "geese"], q: "swarm", a: "bees", o: ["honey", "sting", "hive"], why: "the animals that group belongs to" },
  { pair: ["shepherd", "sheep"], q: "beekeeper", a: "bees", o: ["honey", "smoke", "veil"], why: "the animal they look after" },
  { pair: ["sand", "beach"], q: "snow", a: "mountain", o: ["cold", "white", "melt"], why: "where you find it lying" },
  { pair: ["nib", "pen"], q: "blade", a: "knife", o: ["sharp", "cut", "steel"], why: "the tool it is the working end of" },
  { pair: ["twelve", "dozen"], q: "hundred", a: "century", o: ["thousand", "many", "score"], why: "the word for that number" },
  { pair: ["hungry", "eat"], q: "tired", a: "sleep", o: ["yawn", "bed", "night"], why: "what you do about it" },
  { pair: ["floor", "ceiling"], q: "first", a: "last", o: ["second", "start", "number"], why: "the opposite end" },
  { pair: ["puzzle", "solve"], q: "knot", a: "untie", o: ["rope", "tight", "pull"], why: "what you do to it" },
  { pair: ["oak", "acorn"], q: "apple tree", a: "apple", o: ["blossom", "orchard", "leaf"], why: "the fruit it drops" },
  { pair: ["short", "shorter"], q: "good", a: "better", o: ["best", "goodly", "well"], why: "the more-than form" },
  { pair: ["water", "thirst"], q: "food", a: "hunger", o: ["plate", "cook", "taste"], why: "what it cures" },
  { pair: ["train", "rails"], q: "boat", a: "water", o: ["sail", "harbour", "anchor"], why: "what it travels on" },
  { pair: ["bulb", "light"], q: "radiator", a: "heat", o: ["metal", "wall", "pipe"], why: "what it gives out" },
  { pair: ["cook", "raw"], q: "dry", a: "wet", o: ["towel", "sun", "warm"], why: "the state it starts from" },
  { pair: ["wheel", "roll"], q: "hinge", a: "swing", o: ["door", "metal", "screw"], why: "the movement it allows" },
  { pair: ["herd", "cattle"], q: "flock", a: "birds", o: ["feather", "wing", "sky"], why: "the animals that group belongs to" },
];

/* Common short words, for building word ladders. Density matters more than
   size here: a ladder needs neighbours, so this is deliberately thick with
   three- and four-letter words that differ by one letter. */
export const LADDER_WORDS = [
  "BAT", "BIT", "BUT", "BAD", "BED", "BID", "BUD", "BAG", "BEG", "BIG", "BOG", "BUG", "BAN", "BEN", "BIN", "BUN",
  "CAT", "COT", "CUT", "CAP", "COP", "CUP", "CAN", "CON", "CAR", "COW", "COD", "CUB", "CUE",
  "DAY", "DEN", "DIN", "DON", "DOG", "DIG", "DUG", "DOT", "DIP", "DAM", "DIM",
  "EAR", "EAT", "EGG", "END", "EYE",
  "FAN", "FUN", "FIN", "FAT", "FIT", "FOG", "FAR", "FUR", "FEW", "FIG", "FIX", "FLY",
  "GAP", "GAS", "GET", "GOT", "GUN", "GUM", "GYM", "GOD",
  "HAT", "HIT", "HOT", "HUT", "HAM", "HIM", "HUM", "HEN", "HIP", "HOP", "HAS", "HIS",
  "ICE", "ILL", "INK", "INN",
  "JAM", "JAR", "JET", "JOB", "JOG", "JOY", "JUG",
  "KEY", "KID", "KIT",
  "LAP", "LIP", "LOP", "LAB", "LAD", "LED", "LID", "LOG", "LEG", "LET", "LOT", "LOW", "LAW",
  "MAD", "MAN", "MAP", "MAT", "MEN", "MET", "MUD", "MUG", "MIX", "MOP", "MOB", "MOW",
  "NET", "NIT", "NOT", "NUT", "NAP", "NEW", "NOW", "NOD",
  "OAK", "ODD", "OIL", "OLD", "ONE", "OUR", "OUT", "OWL", "OWN",
  "PAN", "PEN", "PIN", "PUN", "PAT", "PET", "PIT", "POT", "PUT", "PAD", "POD", "PIG", "PEG", "PAY", "PIE", "POP", "PUP",
  "RAT", "RAN", "RUN", "RUG", "RIG", "RIB", "RED", "RID", "ROD", "ROW", "RAW", "RAY", "RIP", "ROT",
  "SAD", "SAT", "SET", "SIT", "SUN", "SIN", "SON", "SIP", "SAP", "SAW", "SAY", "SEA", "SEE", "SKY", "SPY", "SIX",
  "TAP", "TIP", "TOP", "TAN", "TEN", "TIN", "TON", "TAG", "TUG", "TOE", "TOY", "TRY", "TWO", "THE",
  "VAN", "VET",
  "WAR", "WAS", "WAX", "WAY", "WEB", "WET", "WIG", "WIN", "WON", "WIT", "WAG",
  "YES", "YET", "YOU",
  "ZIP", "ZOO",
  "BAKE", "CAKE", "LAKE", "MAKE", "RAKE", "TAKE", "WAKE", "LANE", "CANE", "MANE", "PANE", "BONE", "CONE", "GONE",
  "BAND", "BEND", "BIND", "BOND", "FIND", "FUND", "HAND", "LAND", "LEND", "MEND", "MIND", "SAND", "SEND", "WIND",
  "BALL", "BELL", "BILL", "BULL", "CALL", "CELL", "FALL", "FILL", "FULL", "HALL", "HILL", "HULL", "MILL", "PULL",
  "TALL", "TELL", "TILL", "WALL", "WELL", "WILL",
  "BEAR", "BEAD", "BEAM", "BEAN", "BEAT", "HEAR", "HEAD", "HEAP", "HEAT", "NEAR", "NEAT", "PEAR", "PEAK", "PEAT",
  "READ", "REAL", "SEAL", "SEAM", "SEAT", "TEAM", "TEAR", "YEAR", "MEAL", "MEAT", "MEAN",
  "BOAT", "COAT", "GOAT", "MOAT", "COST", "CAST", "CASE", "CAVE", "CAME", "CARE", "CARD", "CART", "CORD", "CORE",
  "FACE", "FACT", "FADE", "FAME", "FARE", "FARM", "FAST", "FEAR", "FEAT", "FEED", "FEEL", "FEET",
  "GATE", "GAME", "GAVE", "HATE", "HAVE", "HERE", "HIDE", "HIRE", "HOLE", "HOME", "HOPE", "HOSE", "HOST",
  "LAST", "LATE", "LIFE", "LIKE", "LIME", "LINE", "LIVE", "LOSE", "LOST", "LOVE",
  "MAZE", "MICE", "MILE", "MINE", "MODE", "MOLE", "MORE", "MOST", "MOVE", "MUST",
  "NAME", "NICE", "NINE", "NOSE", "NOTE", "PACE", "PACK", "PAGE", "PAIN", "PAIR", "PALE", "PARK", "PART", "PAST",
  "PICK", "PILE", "PINE", "PIPE", "PLAN", "PLAY", "POLE", "PORT", "POSE", "POST", "PURE",
  "RACE", "RAIN", "RATE", "RICE", "RIDE", "RING", "RIPE", "RISE", "ROAD", "ROBE", "ROCK", "ROLE", "ROSE", "RULE",
  "SAFE", "SAGE", "SAIL", "SALE", "SAME", "SAVE", "SHIP", "SHOP", "SHOT", "SIDE", "SIGN", "SILK", "SING", "SITE",
  "SIZE", "SLIP", "SLOW", "SNOW", "SOFT", "SOLD", "SOME", "SONG", "SOON", "SORT", "SPIN", "STAR", "STAY", "STEM",
  "STEP", "STOP", "SUCH", "SUIT", "SURE",
  "TAKE", "TALE", "TALK", "TAME", "TAPE", "TASK", "TEAL", "TENT", "TEST", "THAN", "THAT", "THEM", "THEN", "THIN",
  "THIS", "TIDE", "TIED", "TILE", "TIME", "TINY", "TIRE", "TONE", "TOOK", "TOOL", "TORN", "TOUR", "TOWN", "TREE",
  "TRIP", "TRUE", "TUBE", "TUNE", "TURN",
  "VASE", "VERY", "VIEW", "VINE", "VOTE",
  "WAGE", "WAIT", "WAKE", "WALK", "WANT", "WARM", "WASH", "WAVE", "WEAK", "WEAR", "WEEK", "WENT", "WERE", "WEST",
  "WHAT", "WHEN", "WIDE", "WIFE", "WILD", "WINE", "WING", "WIRE", "WISE", "WISH", "WITH", "WOOD", "WOOL", "WORD",
  "WORE", "WORK", "WORM", "YARD", "YARN", "ZONE",
];

/* Names and category sets for the logic and liar puzzles. Names are short and
   easy to hold in your head, because the puzzle is the reasoning, not the
   spelling. */
export const NAMES = ["Ana", "Ben", "Cara", "Dev", "Elsa", "Finn", "Gus", "Hana", "Iris", "Jack"];

export const LOGIC_SETS = [
  { of: "pet", plural: "pets", items: ["a cat", "a dog", "a rabbit", "a parrot"], short: ["cat", "dog", "rabbit", "parrot"] },
  { of: "hat", plural: "hats", items: ["a red hat", "a blue hat", "a green hat", "a yellow hat"], short: ["red", "blue", "green", "yellow"] },
  { of: "snack", plural: "snacks", items: ["an apple", "a banana", "a plum", "a pear"], short: ["apple", "banana", "plum", "pear"] },
  { of: "hobby", plural: "hobbies", items: ["chess", "football", "painting", "dancing"], short: ["chess", "football", "painting", "dancing"] },
  { of: "seat", plural: "seats", items: ["the front seat", "the middle seat", "the back seat", "the corner seat"], short: ["front", "middle", "back", "corner"] },
  { of: "instrument", plural: "instruments", items: ["the piano", "the drum", "the flute", "the violin"], short: ["piano", "drum", "flute", "violin"] },
];
