/* The written content: words for the letter puzzles, riddles for Wick, and the
   little category sets the word-odd-one-out is built from.

   All of it is plain data with no DOM and no imports, so tools/bloom-sim.mjs
   can load it in Node and check every entry (see the checks at the bottom of
   that file: uppercase A-Z only, a hint on every word, four options and
   exactly one answer on every riddle).

   Audience is a nine-year-old, so the rule for a word earning its place here
   is that a nine-year-old could spell it unprompted. */

/* Words for Scramble and Word Hunt. `n` is the length, which is what the
   difficulty ladder selects on: short words are easy to unscramble, long ones
   with repeated or awkward letters are not. */
export const WORDS = [
  // --- 3 letters: only ever used to hide inside a Word Hunt grid ---
  { w: "CAT", hint: "Sleeps sixteen hours a day" },
  { w: "OWL", hint: "Awake when you are not" },
  { w: "FOX", hint: "Red, clever, bushy tail" },
  { w: "BEE", hint: "Makes honey, hums" },
  { w: "SUN", hint: "The star we live next to" },
  { w: "MAP", hint: "Paper that knows where things are" },
  { w: "JAM", hint: "Squashed fruit on toast" },
  { w: "ICE", hint: "Water that stopped moving" },
  { w: "KEY", hint: "Opens a lock" },
  { w: "PIE", hint: "Filling with a pastry lid" },
  { w: "BUG", hint: "Six legs, usually in the garden" },
  { w: "OAK", hint: "The tree acorns come from" },
  { w: "FIG", hint: "A fruit full of tiny seeds" },
  { w: "ELF", hint: "Small, pointy ears, storybooks" },
  { w: "NET", hint: "Catches fish, or a butterfly" },
  { w: "PUP", hint: "A very young dog" },
  { w: "MUD", hint: "Dirt plus rain" },
  { w: "ZIP", hint: "Two rows of teeth on a coat" },

  // --- 4 letters ---
  { w: "MOON", hint: "Goes round the Earth" },
  { w: "STAR", hint: "A point of light at night" },
  { w: "LEAF", hint: "Green, falls in autumn" },
  { w: "FROG", hint: "Green, hops, says ribbit" },
  { w: "BOAT", hint: "Floats and carries you" },
  { w: "CAKE", hint: "Comes with candles on it" },
  { w: "RAIN", hint: "Falls out of grey clouds" },
  { w: "WIND", hint: "Air in a hurry" },
  { w: "NEST", hint: "Where eggs wait" },
  { w: "SNOW", hint: "Cold, white, quiet" },
  { w: "FISH", hint: "Breathes underwater" },
  { w: "BIRD", hint: "Feathers and a beak" },
  { w: "TREE", hint: "Wooden, tall, full of leaves" },
  { w: "BOOK", hint: "Pages full of story" },
  { w: "LAMP", hint: "Makes a room less dark" },
  { w: "DOOR", hint: "You knock on it" },
  { w: "GIFT", hint: "Wrapped, with your name on it" },
  { w: "KITE", hint: "Flies on a string" },
  { w: "MILK", hint: "White, from a cow" },
  { w: "SOCK", hint: "One always goes missing" },
  { w: "DUCK", hint: "Quacks, likes ponds" },
  { w: "BELL", hint: "Rings when you shake it" },
  { w: "CORN", hint: "Grows in yellow rows" },
  { w: "SAND", hint: "The beach, up close" },
  { w: "ROCK", hint: "Heavy, grey, very patient" },
  { w: "WOLF", hint: "Howls at that moon" },
  { w: "CROW", hint: "Black bird, very clever" },
  { w: "HIVE", hint: "A city made of wax" },
  { w: "FERN", hint: "A feathery plant of the shade" },
  { w: "MOSS", hint: "Green velvet on a stone" },
  { w: "PLUM", hint: "Purple fruit with a stone inside" },
  { w: "PEAR", hint: "Fruit shaped like a raindrop" },
  { w: "SWAN", hint: "White, long neck, bad temper" },
  { w: "MOLE", hint: "Digs, and can barely see" },
  { w: "CLAM", hint: "Shuts tight, lives in sand" },
  { w: "DAWN", hint: "The first light of the day" },
  { w: "MASK", hint: "Hides the face behind it" },
  { w: "RAFT", hint: "Logs tied together to float" },

  // --- 5 letters ---
  { w: "CLOUD", hint: "Made of water, floats anyway" },
  { w: "RIVER", hint: "Always going to the sea" },
  { w: "STONE", hint: "You skim it across a pond" },
  { w: "HONEY", hint: "Golden, sticky, made by bees" },
  { w: "APPLE", hint: "Crunchy, red or green" },
  { w: "TIGER", hint: "Orange with black stripes" },
  { w: "ZEBRA", hint: "A horse in stripy pyjamas" },
  { w: "WHALE", hint: "The biggest animal there is" },
  { w: "SNAIL", hint: "Carries its house on its back" },
  { w: "MOUSE", hint: "Small, grey, likes cheese" },
  { w: "SHEEP", hint: "Wool on legs" },
  { w: "HORSE", hint: "You ride it, it has a mane" },
  { w: "BEACH", hint: "Where the sand meets the sea" },
  { w: "STORM", hint: "Wind and rain, all shouting" },
  { w: "LIGHT", hint: "The opposite of dark" },
  { w: "NIGHT", hint: "When the stars come out" },
  { w: "SUGAR", hint: "Sweet white grains" },
  { w: "BREAD", hint: "Baked, sliced, toasted" },
  { w: "JUICE", hint: "Squeezed out of fruit" },
  { w: "CANDY", hint: "Sweet, and never enough" },
  { w: "PIANO", hint: "Black and white keys" },
  { w: "DRUM", hint: "You hit it to make music" },
  { w: "PAINT", hint: "Colour in a tube" },
  { w: "BRUSH", hint: "Moves the paint about" },
  { w: "CHALK", hint: "Draws on a pavement" },
  { w: "SPOON", hint: "For soup, not for steak" },
  { w: "CHAIR", hint: "Four legs, holds you up" },
  { w: "CLOCK", hint: "Its hands never stop" },
  { w: "TRAIN", hint: "Runs on rails, very long" },
  { w: "PLANE", hint: "Wings, but no feathers" },
  { w: "ROBOT", hint: "A machine that does jobs" },
  { w: "GHOST", hint: "Sheet with two holes" },
  { w: "CROWN", hint: "A hat only a king wears" },
  { w: "SWORD", hint: "Knights carry one" },
  { w: "TOWER", hint: "Very tall, one room wide" },
  { w: "GRASS", hint: "Green, and needs cutting" },
  { w: "BERRY", hint: "Small fruit off a bush" },
  { w: "LEMON", hint: "Yellow and very sour" },
  { w: "PEACH", hint: "Fuzzy skin, sweet inside" },
  { w: "ONION", hint: "Layers, and it makes you cry" },
  { w: "OTTER", hint: "Holds hands while it sleeps" },
  { w: "PANDA", hint: "Black and white, eats bamboo" },
  { w: "KOALA", hint: "Sleepy, grey, in a gum tree" },
  { w: "CAMEL", hint: "Crosses deserts with a hump" },
  { w: "EAGLE", hint: "Sharp eyes, big wings" },
  { w: "ROBIN", hint: "Small bird with a red front" },
  { w: "TRUNK", hint: "An elephant's nose, or a tree's middle" },
  { w: "CANOE", hint: "A narrow boat you paddle" },
  { w: "IGLOO", hint: "A house made of snow blocks" },
  { w: "COMET", hint: "A snowball with a tail, in space" },
  { w: "ORBIT", hint: "The loop a moon travels" },
  { w: "MAPLE", hint: "Its leaf is on a flag" },
  { w: "OCEAN", hint: "Bigger than a sea" },
  { w: "SHELL", hint: "The beach keeps these" },
  { w: "TEETH", hint: "More than one tooth" },
  { w: "SMILE", hint: "What a joke makes you do" },

  // --- 6 letters ---
  { w: "PLANET", hint: "A world going round a sun" },
  { w: "ROCKET", hint: "Goes up with a lot of noise" },
  { w: "GARDEN", hint: "Where things are grown on purpose" },
  { w: "FLOWER", hint: "Petals on a stem" },
  { w: "FOREST", hint: "Trees, and more trees" },
  { w: "MEADOW", hint: "A field of long grass" },
  { w: "CASTLE", hint: "Stone walls and a moat" },
  { w: "DRAGON", hint: "Scales, wings and fire" },
  { w: "WIZARD", hint: "Pointy hat, long beard" },
  { w: "PUZZLE", hint: "What you are doing right now" },
  { w: "RIDDLE", hint: "A question that hides its answer" },
  { w: "SECRET", hint: "Don't tell anyone" },
  { w: "BUTTON", hint: "Push it, or sew it on" },
  { w: "PENCIL", hint: "Wood outside, grey inside" },
  { w: "MARKER", hint: "A thick, bright pen" },
  { w: "BOTTLE", hint: "Glass, with a neck" },
  { w: "BASKET", hint: "You carry apples in it" },
  { w: "WINDOW", hint: "A hole for the light" },
  { w: "LADDER", hint: "Stairs you can carry" },
  { w: "BRIDGE", hint: "Gets you over the water" },
  { w: "TUNNEL", hint: "A road through a hill" },
  { w: "ISLAND", hint: "Land with sea all round it" },
  { w: "DESERT", hint: "Sand, sun and no rain" },
  { w: "JUNGLE", hint: "Hot forest, full of noise" },
  { w: "CANYON", hint: "A crack in the world" },
  { w: "VALLEY", hint: "The low bit between hills" },
  { w: "SPRING", hint: "The season after winter" },
  { w: "AUTUMN", hint: "When the leaves let go" },
  { w: "WINTER", hint: "The cold one" },
  { w: "SUMMER", hint: "The one with the long holiday" },
  { w: "MONKEY", hint: "Swings, and steals your banana" },
  { w: "TURTLE", hint: "Slow, and never locked out" },
  { w: "RABBIT", hint: "Long ears, quick feet" },
  { w: "DONKEY", hint: "Grey, stubborn, loud" },
  { w: "PARROT", hint: "Repeats what you said" },
  { w: "PENGUIN", hint: "A bird in a dinner suit" },
  { w: "SPIDER", hint: "Eight legs, builds traps" },
  { w: "BEETLE", hint: "A bug in shiny armour" },
  { w: "SALMON", hint: "Swims upstream to get home" },
  { w: "WALRUS", hint: "Whiskers and two long tusks" },
  { w: "CHEESE", hint: "What you say to a camera" },
  { w: "BUTTER", hint: "Spread it on the bread" },
  { w: "COOKIE", hint: "Round, sweet, with chips in" },
  { w: "BANANA", hint: "Yellow, and you peel it" },
  { w: "CARROT", hint: "Orange, and rabbits agree" },
  { w: "POTATO", hint: "Grows underground, becomes chips" },
  { w: "PEPPER", hint: "Makes you sneeze" },
  { w: "GUITAR", hint: "Six strings to strum" },
  { w: "VIOLIN", hint: "Played with a bow" },
  { w: "CIRCLE", hint: "A shape with no corners" },
  { w: "SQUARE", hint: "Four sides, all the same" },
  { w: "SHADOW", hint: "Follows you but is never late" },
  { w: "MIRROR", hint: "Shows you back to front" },
  { w: "SILVER", hint: "The colour of a coin" },
  { w: "GOLDEN", hint: "The colour of treasure" },
  { w: "PURPLE", hint: "Red and blue, mixed" },
  { w: "ORANGE", hint: "A colour and a fruit" },
  { w: "YELLOW", hint: "The colour of the sun" },
  { w: "FRIEND", hint: "Who you'd share the last cookie with" },

  // --- 7 letters ---
  { w: "RAINBOW", hint: "Seven colours after the rain" },
  { w: "THUNDER", hint: "The noise after the flash" },
  { w: "DIAMOND", hint: "The hardest sparkly stone" },
  { w: "TREASURE", hint: "What the X marks" },
  { w: "MERMAID", hint: "Half girl, half fish" },
  { w: "UNICORN", hint: "A horse with one horn" },
  { w: "MONSTER", hint: "Lives under the bed" },
  { w: "PUMPKIN", hint: "Orange, hollowed out in October" },
  { w: "BLOSSOM", hint: "The flowers a tree wears in spring" },
  { w: "COMPASS", hint: "Its needle always finds north" },
  { w: "LANTERN", hint: "A light you carry by its handle" },
  { w: "WHISPER", hint: "Talking very quietly" },
  { w: "BALLOON", hint: "Full of air until it isn't" },
  { w: "BLANKET", hint: "You pull it up in winter" },
  { w: "CABBAGE", hint: "A vegetable of many layers" },
  { w: "PELICAN", hint: "A bird with a bag on its face" },
  { w: "DOLPHIN", hint: "Clever, grey, and always smiling" },
  { w: "OCTOPUS", hint: "Eight arms, no bones" },
  { w: "PEACOCK", hint: "Shows off a fan of feathers" },
  { w: "GIRAFFE", hint: "Reaches the top leaves" },
  { w: "LEOPARD", hint: "Spotted, and cannot change them" },
  { w: "HAMSTER", hint: "Runs all night in a wheel" },
  { w: "MAGNETS", hint: "They pull, or they push" },
  { w: "VOLCANO", hint: "A mountain that has had enough" },
  { w: "TEACHER", hint: "Sets the homework" },
  { w: "JOURNEY", hint: "Going a long way from here" },
  { w: "MYSTERY", hint: "Nobody has solved it yet" },
];

/* Riddles for Wick. Four options, and `a` is the index of the true one.
   Everything a nine-year-old can get to by thinking, with nothing that turns
   on a pun only an adult knows. */
export const RIDDLES = [
  { q: "I have hands but cannot clap. What am I?", o: ["A clock", "A glove", "A statue", "A tree"], a: 0 },
  { q: "I get wetter the more I dry. What am I?", o: ["A sponge", "A towel", "A puddle", "A cloud"], a: 1 },
  { q: "What has a neck but no head?", o: ["A snake", "A bottle", "A ladder", "A river"], a: 1 },
  { q: "What goes up but never comes down?", o: ["A balloon", "Your age", "A kite", "Smoke"], a: 1 },
  { q: "I follow you all day and vanish at night. What am I?", o: ["Your dog", "Your shadow", "The wind", "Your name"], a: 1 },
  { q: "What has teeth but cannot bite?", o: ["A comb", "A pillow", "A cloud", "A shoe"], a: 0 },
  { q: "What has an eye but cannot see?", o: ["A potato", "A needle", "A window", "A cat"], a: 1 },
  { q: "What has legs but never walks?", o: ["A table", "A snake", "A fish", "A worm"], a: 0 },
  { q: "The more of me you take, the more you leave behind. What am I?", o: ["Money", "Footsteps", "Water", "Time"], a: 1 },
  { q: "What has a face and two hands but no arms?", o: ["A doll", "A clock", "A coin", "A mask"], a: 1 },
  { q: "What can travel the world while staying in one corner?", o: ["A stamp", "A globe", "A map", "A spider"], a: 0 },
  { q: "What has many keys but opens no doors?", o: ["A janitor", "A piano", "A keyring", "A car"], a: 1 },
  { q: "I am full of holes but I still hold water. What am I?", o: ["A net", "A sponge", "A bucket", "A sieve"], a: 1 },
  { q: "What gets bigger the more you take away from it?", o: ["A hole", "A cake", "A balloon", "A shadow"], a: 0 },
  { q: "What runs but never gets tired?", o: ["A river", "A dog", "A clock", "An athlete"], a: 0 },
  { q: "What can you catch but never throw?", o: ["A ball", "A cold", "A fish", "A bus"], a: 1 },
  { q: "What has a bed but never sleeps?", o: ["A hotel", "A river", "A baby", "A garden"], a: 1 },
  { q: "What has one eye but cannot wink?", o: ["A pirate", "A storm", "A cyclops", "A camera"], a: 1 },
  { q: "What goes through towns and hills but never moves?", o: ["A road", "A train", "A wind", "A cloud"], a: 0 },
  { q: "What is easy to lift but hard to throw?", o: ["A pillow", "A feather", "A balloon", "A pencil"], a: 1 },
  { q: "I have branches but no fruit, trunk or leaves. What am I?", o: ["A river", "A bank", "A road", "A cloud"], a: 1 },
  { q: "What has a thumb and four fingers but is not alive?", o: ["A statue", "A glove", "A drawing", "A robot"], a: 1 },
  { q: "What kind of band never plays music?", o: ["A rubber band", "A brass band", "A rock band", "A school band"], a: 0 },
  { q: "What has a ring but no finger?", o: ["A tree", "A telephone", "A door", "A planet"], a: 1 },
  { q: "What gets sharper the more you use it?", o: ["A knife", "Your brain", "A pencil", "A saw"], a: 1 },
  { q: "What is always in front of you but cannot be seen?", o: ["Air", "The future", "A ghost", "Glass"], a: 1 },
  { q: "What building has the most stories?", o: ["A tower", "A library", "A castle", "A school"], a: 1 },
  { q: "What flies without wings?", o: ["Time", "A rocket", "A seed", "A stone"], a: 0 },
  { q: "What has a bottom at the top?", o: ["A hill", "Your legs", "A cup", "A tree"], a: 1 },
  { q: "Where does today come before yesterday?", o: ["In a dream", "In a dictionary", "On a calendar", "In the past"], a: 1 },
  { q: "What has words but never speaks?", o: ["A book", "A parrot", "A radio", "A phone"], a: 0 },
  { q: "What breaks when you say its name out loud?", o: ["Glass", "Silence", "A promise", "An egg"], a: 1 },
  { q: "What has a head and a tail but no body?", o: ["A snake", "A coin", "A comet", "A kite"], a: 1 },
  { q: "What can fill a room but takes up no space?", o: ["Air", "Light", "Water", "Dust"], a: 1 },
  { q: "What has four wheels and flies?", o: ["A plane", "A bin lorry", "A kite", "A car"], a: 1 },
  { q: "What has a spine but no bones?", o: ["A jellyfish", "A book", "A cactus", "A worm"], a: 1 },
  { q: "What can you break without touching it?", o: ["A promise", "A window", "A stick", "A plate"], a: 0 },
  { q: "What is so fragile that saying its name breaks it? (Not silence!)", o: ["A bubble", "An egg", "A secret", "Ice"], a: 2 },
  { q: "What has a mouth but never eats?", o: ["A cave", "A river", "A jar", "A mask"], a: 1 },
  { q: "What has a tongue but cannot taste?", o: ["A shoe", "A bell", "A snake", "A cat"], a: 0 },
  { q: "What is always coming but never arrives?", o: ["Tomorrow", "The post", "The bus", "Winter"], a: 0 },
  { q: "What has bark but no bite?", o: ["A puppy", "A tree", "A seal", "A fox"], a: 1 },
  { q: "What can go up a chimney down, but not down a chimney up?", o: ["Smoke", "An umbrella", "Santa", "A bird"], a: 1 },
  { q: "The person who makes it does not want it. Who wants it never uses it. What is it?", o: ["A coffin", "A key", "A trap", "A cage"], a: 0 },
  { q: "What weighs more, a kilo of feathers or a kilo of bricks?", o: ["The feathers", "The bricks", "They are the same", "It depends"], a: 2 },
  { q: "How many months have 28 days?", o: ["One", "Two", "All twelve", "Four"], a: 2 },
  { q: "If a rooster lays an egg on a roof, which way does it roll?", o: ["Left", "Right", "Straight down", "Roosters do not lay eggs"], a: 3 },
  { q: "You are in a race and overtake the runner in second place. What place are you in?", o: ["First", "Second", "Third", "Last"], a: 1 },
  { q: "A farmer has 17 sheep and all but 9 run away. How many are left?", o: ["8", "9", "17", "0"], a: 1 },
  { q: "What can you hold in your left hand but never in your right?", o: ["A pencil", "Your right elbow", "A shadow", "A thought"], a: 1 },
  { q: "Two mothers and two daughters go fishing and catch three fish, one each. How?", o: ["One cheated", "They shared", "There were only three: a grandma, a mum and a girl", "One fish was cut up"], a: 2 },
  { q: "What goes on four legs in the morning, two at noon and three at night?", o: ["A dog", "A person, over a whole life", "A table", "A spider"], a: 1 },
  { q: "I am tall when I am young and short when I am old. What am I?", o: ["A tree", "A candle", "A giraffe", "A shadow"], a: 1 },
  { q: "What has a hundred legs but cannot stand up?", o: ["A centipede", "A caterpillar", "Fifty pairs of trousers", "A ladder"], a: 2 },
  { q: "What comes down but never goes up?", o: ["Rain", "A lift", "A ball", "A leaf"], a: 0 },
  { q: "What is black when clean and white when dirty?", o: ["A blackboard", "A shoe", "A cat", "A window"], a: 0 },
  { q: "What has an end but no beginning, and no middle either?", o: ["A rope", "A circle", "A doughnut", "A road"], a: 2 },
  { q: "Which is heavier: a tonne of gold or a tonne of grass?", o: ["Gold", "Grass", "Neither, they match", "Gold, always"], a: 2 },
  { q: "What kind of room has no doors or windows?", o: ["A cellar", "A mushroom", "A cupboard", "A tent"], a: 1 },
  { q: "What sits in a corner but travels round the world?", o: ["A stamp", "A cat", "A globe", "A spider"], a: 0 },
  { q: "You see a boat full of people but not one person on board. How?", o: ["They are hiding", "They are all married", "It is a ghost boat", "They swam off"], a: 1 },
  { q: "What is at the end of a rainbow?", o: ["Gold", "The letter W", "Rain", "A pot"], a: 1 },
];

/* Sets for the word odd-one-out. Three members of `in` are shown with one
   member of `out`, and the odd one is the outsider. The categories are chosen
   so that the outsider is wrong for a reason you can say out loud - which is
   what `why` is: the line shown once the answer is in. */
export const CATEGORIES = [
  { name: "fruit", in: ["APPLE", "PEAR", "PLUM", "PEACH", "BANANA", "CHERRY", "GRAPE", "MANGO"], out: ["CARROT", "ONION", "POTATO", "CABBAGE"], why: "The others are fruit." },
  { name: "animals with wings", in: ["OWL", "CROW", "EAGLE", "ROBIN", "BAT", "SWAN"], out: ["FOX", "MOLE", "OTTER", "CAMEL"], why: "The others can fly." },
  { name: "things in the sky", in: ["MOON", "STAR", "CLOUD", "COMET", "SUN", "RAINBOW"], out: ["RIVER", "STONE", "MOSS", "TUNNEL"], why: "The others are up in the sky." },
  { name: "things you read", in: ["BOOK", "MAP", "LETTER", "COMIC", "SIGN", "MENU"], out: ["SPOON", "LADDER", "SOCK", "KETTLE"], why: "The others are things you read." },
  { name: "cold things", in: ["SNOW", "ICE", "FROST", "IGLOO", "HAIL"], out: ["OVEN", "DESERT", "FLAME", "SUMMER"], why: "The others are cold." },
  { name: "instruments", in: ["PIANO", "GUITAR", "VIOLIN", "DRUM", "FLUTE", "HARP"], out: ["HAMMER", "PENCIL", "KETTLE", "LADDER"], why: "The others make music." },
  { name: "sea animals", in: ["WHALE", "SHARK", "OCTOPUS", "DOLPHIN", "CRAB", "SALMON"], out: ["TIGER", "PANDA", "DONKEY", "SPIDER"], why: "The others live in the sea." },
  { name: "colours", in: ["PURPLE", "YELLOW", "SILVER", "GREEN", "ORANGE", "SCARLET"], out: ["CIRCLE", "MONDAY", "PENCIL", "WINTER"], why: "The others are colours." },
  { name: "things with wheels", in: ["TRAIN", "BICYCLE", "TRACTOR", "SCOOTER", "WAGON"], out: ["CANOE", "LADDER", "KITE", "SLEDGE"], why: "The others have wheels." },
  { name: "parts of a tree", in: ["LEAF", "TRUNK", "ROOT", "BRANCH", "BARK", "TWIG"], out: ["FEATHER", "PEBBLE", "BUTTON", "WHISKER"], why: "The others are parts of a tree." },
  { name: "weather", in: ["RAIN", "SNOW", "THUNDER", "WIND", "FOG", "STORM"], out: ["PIANO", "CASTLE", "COOKIE", "MARBLE"], why: "The others are weather." },
  { name: "things in a kitchen", in: ["SPOON", "KETTLE", "PLATE", "OVEN", "WHISK", "BOWL"], out: ["ANCHOR", "SADDLE", "TELESCOPE", "PARACHUTE"], why: "The others belong in a kitchen." },
  { name: "numbers", in: ["SEVEN", "TWELVE", "THIRTY", "NINE", "FORTY"], out: ["PURPLE", "SPOON", "TUESDAY", "MEADOW"], why: "The others are numbers." },
  { name: "days", in: ["MONDAY", "FRIDAY", "SUNDAY", "TUESDAY"], out: ["JANUARY", "AUTUMN", "MORNING", "EASTER"], why: "The others are days of the week." },
  { name: "things that float", in: ["RAFT", "BOAT", "CORK", "BUBBLE", "CANOE"], out: ["ANCHOR", "HAMMER", "BOULDER", "COIN"], why: "The others float." },
];
